import QtQuick 2.0

Item {
    property variant palette: {
        "AppBarItem":           "black",
        "AppBarItemSelected":   "white",
        "Text":                 "white",
        "TextPressed":          "black",
        "DisabledText":         "darkGray",
        "ButtonTextDisabled":   "#202020",
        "DropDown" :            "white",
        "DropDownPressed" :     "black",
        "DropDownPersonalization" : "black",
        "PaneBackground" :      "black",
        "PushButton" :          "white",
        "PushButtonPressed" :   "black",
        "PushButtonSelected":   "black",
        "SectionBackground":    "lightGray",
        "SectionForeground":    "black",
        "MenuHighlight":        "white",
        "MenuHighlightedText":  "black",
        "MenuTitle":            "black",
        "SearchFieldBackground": Qt.rgba(0.62, 0.62, 0.62, 0.2),
        "DialogTitleText":      "white",
        "DialogGradientStart":  "black",
        "DialogGradientEnd":    "black",
        "HeaderTitle":          "white",
        "AppGridButtonText":    "white",
        "AppGridButtonTextActive":"black",
        "SpecialKeyTop":        "gray",
        "SpecialKeyMid":        "#555555",
        "SpecialKeyBot":        "#3c3c3c",
        "LetterKeyTop":         "#757575",
        "LetterKeyBot":         "#fcfcfc",
        "ServiceKeyTop":        "#bdbdbd",
        "ServiceKeyBot":        "#242427",
        "NumberKeyTop":         "#747474",
        "NumberKeyMid":         "#616161",
        "NumberKeyBot":         "#8b8b8b",
        "KeyboardBackgroundTop":"#242427",
        "KeyboardBackgroundMid":"#3a3a3a",
        "KeyboardBackgroundBot":"#15151f",
        "SpecialKeyText":       "white",
        "LetterKeyText":        "black",
        "ServiceKeyText":       "white",
        "NumberKeyText":        "white",
        "CallBorderColor":      "white"
    }
}
