import QtQuick 2.0

Item {
    property variant palette: {
        "AppBarItem":           "black",
        "AppBarItemSelected":   "white",
        "Text":                 "white",
        "TextPressed":          "black",
        "DisabledText":         "darkGray",
        "ButtonTextDisabled":   "darkGray",
        "DropDown" :            "black",
        "DropDownPressed" :     "white",
        "DropDownPersonalization" : "black",
        "PaneBackground" :      "black",
        "PushButton" :          "black",
        "PushButtonPressed" :   "white",
        "PushButtonSelected":   "white",
        "SectionBackground":    "LightSkyBlue",
        "SectionForeground":    "black",
        "MenuHighlight":        "LightSkyBlue",
        "MenuHighlightedText":  "black",
        "MenuTitle":            "white",
        "SearchFieldBackground": Qt.rgba(0.318, 0.78, 0.914, 0.5),
        "DialogTitleText":      "white",
        "DialogGradientStart":  "black",
        "DialogGradientEnd":    "black",
        "HeaderTitle":          "white",
        "AppGridButtonText":    "white",
        "AppGridButtonTextActive":"white",
        "SpecialKeyTop":        "#808080",
        "SpecialKeyMid":        "#555555",
        "SpecialKeyBot":        "#3c3c3c",
        "LetterKeyTop":         "#2f4b56",
        "LetterKeyBot":         "#418ca1",
        "ServiceKeyTop":        "#2e474e",
        "ServiceKeyBot":        "#242427",
        "NumberKeyTop":         "#d6d6d6",
        "NumberKeyMid":         "#f0f0f0",
        "NumberKeyBot":         "#ffffff",
        "KeyboardBackgroundTop":"#242427",
        "KeyboardBackgroundMid":"#16353d",
        "KeyboardBackgroundBot":"#15151f",
        "SpecialKeyText":       "white",
        "LetterKeyText":        "white",
        "ServiceKeyText":       "white",
        "NumberKeyText":        "black",
        "CallBorderColor":      "white"
    }
}
