include(applauncher/applauncher.pri)
include(communications/communications.pri)
include(mediaplayer/mediaplayer.pri)
include(navigation/navigation.pri)
include(settings/settings.pri)
#include(tts/tts.pri)
